/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package epharmacysystem.ui.dashboard;

import epharmacysystem.ui.auth.LoginFrame;
import epharmacysystem.data.DataStore;
import epharmacysystem.ui.panels.AdminOrdersPanel;
import epharmacysystem.ui.panels.AdminPrescriptionsPanel;
import epharmacysystem.ui.panels.AdminUsersPanel;
import epharmacysystem.ui.panels.DoctorsOrdersPanel;
import epharmacysystem.ui.panels.DoctorsPrescriptionsPanel;
import epharmacysystem.ui.panels.DoctorsPatientsPanel;
import epharmacysystem.ui.panels.PharmacistsMedicinesPanel;
import java.util.logging.Logger;



/**
 *
 * @author Zid
 */
public class AdminFrame extends javax.swing.JFrame {

    private static final Logger logger = Logger.getLogger(AdminFrame.class.getName());

    private DoctorsPatientsPanel patientsPanel;
    private DoctorsPrescriptionsPanel prescriptionsPanel;
    private DoctorsOrdersPanel doctorsOrderPanel;
    private PharmacistsMedicinesPanel pharmacistsMedicinesPanel;
    private AdminUsersPanel adminUsersPanel;
    private AdminOrdersPanel adminOrdersPanel;
      private AdminPrescriptionsPanel adminPrescriptionsPanel;
    private javax.swing.JPanel activePanel;
    
    public AdminFrame() {

        initComponents();
        setLocationRelativeTo(null);
        pack();
        setMinimumSize(new java.awt.Dimension(900, 500));
        username.setText(DataStore.currentUserName);
        searchField.setVisible(false);
        searchBtn.setVisible(false);
    }

    
    /**
     * Creates new form DoctorFrame
     */
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchBtn1 = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        usersBtn = new javax.swing.JButton();
        prescriptionsBtn = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        ordersBtn = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        medicinesPanel = new javax.swing.JButton();

        searchBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/epharmacysystem/ui/dashboard/search-interface-symbol.png"))); // NOI18N
        searchBtn1.setText("Search");
        searchBtn1.addActionListener(this::searchBtn1ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin's Dashboard");
        setPreferredSize(new java.awt.Dimension(685, 413));

        jLabel1.setFont(new java.awt.Font("Inter 18pt SemiBold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Admin's Dashboard");

        btnLogout.setForeground(new java.awt.Color(255, 51, 51));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        usersBtn.setText("Users");
        usersBtn.addActionListener(this::usersBtnActionPerformed);

        prescriptionsBtn.setText("Prescriptions ");
        prescriptionsBtn.addActionListener(this::prescriptionsBtnActionPerformed);

        username.setFont(new java.awt.Font("Inter 24pt SemiBold", 0, 12)); // NOI18N
        username.setText("Admin (name)");

        ordersBtn.setText("Order Status");
        ordersBtn.addActionListener(this::ordersBtnActionPerformed);

        searchField.setText("Search...");
        searchField.addActionListener(this::searchFieldActionPerformed);

        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/epharmacysystem/ui/dashboard/search-interface-symbol.png"))); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(this::searchBtnActionPerformed);

        medicinesPanel.setText("Medicines");
        medicinesPanel.addActionListener(this::medicinesPanelActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usersBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(prescriptionsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(medicinesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ordersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(292, 292, 292)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                        .addComponent(username)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ordersBtn, usersBtn});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {medicinesPanel, prescriptionsBtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(username)
                    .addComponent(btnLogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(prescriptionsBtn)
                        .addComponent(medicinesPanel)
                        .addComponent(ordersBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchBtn)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {medicinesPanel, ordersBtn, prescriptionsBtn, searchBtn, searchField, usersBtn});

        contentPanel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed

        this.dispose();
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void usersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersBtnActionPerformed

    adminUsersPanel = new AdminUsersPanel();

    contentPanel.removeAll();
    contentPanel.setLayout(new java.awt.BorderLayout());
    contentPanel.add(adminUsersPanel);
    
    contentPanel.revalidate();
    contentPanel.repaint();
    
    
    activePanel = adminUsersPanel;
    searchField.setVisible(true);
    searchField.setText("Search for patients...");
    searchBtn.setVisible(true);
    this.pack();
    }//GEN-LAST:event_usersBtnActionPerformed

    private void prescriptionsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prescriptionsBtnActionPerformed
        // TODO add your handling code here:
    adminPrescriptionsPanel = new AdminPrescriptionsPanel();

    contentPanel.removeAll();
  contentPanel.setLayout(new java.awt.BorderLayout());
    contentPanel.add(adminPrescriptionsPanel);

    contentPanel.revalidate();
    contentPanel.repaint();

    activePanel = adminPrescriptionsPanel;

     searchField.setVisible(true);
    searchField.setText("Search for prescriptions...");
    searchBtn.setVisible(true);
    this.pack();
    }//GEN-LAST:event_prescriptionsBtnActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
    String text = searchField.getText();

    if (activePanel instanceof AdminUsersPanel) {
        ((AdminUsersPanel) activePanel).filterTable(text);
    } 
     else if(activePanel instanceof  PharmacistsMedicinesPanel ) {
        ((PharmacistsMedicinesPanel) activePanel).filterTable(text);
    } 
    else if(activePanel instanceof  AdminOrdersPanel) {
        ((AdminOrdersPanel) activePanel).filterTable(text);
    } 
    }//GEN-LAST:event_searchBtnActionPerformed

    private void searchBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtn1ActionPerformed
      
    }//GEN-LAST:event_searchBtn1ActionPerformed

    private void ordersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersBtnActionPerformed
        adminOrdersPanel = new AdminOrdersPanel();

        contentPanel.removeAll();
      
        contentPanel.add( adminOrdersPanel, java.awt.BorderLayout.CENTER);

        contentPanel.revalidate();
        contentPanel.repaint();

        activePanel =  adminOrdersPanel;
        searchField.setVisible(true);
        searchField.setText("Search for prescriptions...");
        searchBtn.setVisible(true);
        this.pack();
    }//GEN-LAST:event_ordersBtnActionPerformed

    private void medicinesPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicinesPanelActionPerformed
        pharmacistsMedicinesPanel = new PharmacistsMedicinesPanel();

        contentPanel.removeAll();
     contentPanel.setLayout(new java.awt.BorderLayout());
        contentPanel.add(pharmacistsMedicinesPanel, java.awt.BorderLayout.CENTER);

        contentPanel.revalidate();
        contentPanel.repaint();

        activePanel = pharmacistsMedicinesPanel;
        searchField.setVisible(true);
        searchField.setText("Search for medicines...");
        searchBtn.setVisible(true);
        this.pack();
    }//GEN-LAST:event_medicinesPanelActionPerformed

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {

    java.awt.EventQueue.invokeLater(() -> {
        new AdminFrame().setVisible(true);
    });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton medicinesPanel;
    private javax.swing.JButton ordersBtn;
    private javax.swing.JButton prescriptionsBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton searchBtn1;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel username;
    private javax.swing.JButton usersBtn;
    // End of variables declaration//GEN-END:variables
}
