/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package epharmacysystem.ui.dashboard;

import epharmacysystem.ui.auth.LoginFrame;
import epharmacysystem.data.DataStore;
import epharmacysystem.ui.panels.DoctorsOrderPanel;
import epharmacysystem.ui.panels.PrescriptionsPanel;
import epharmacysystem.ui.panels.PatientsPanel;
import java.util.logging.Logger;



/**
 *
 * @author Zid
 */
public class DoctorFrame extends javax.swing.JFrame {

    private static final Logger logger = Logger.getLogger(DoctorFrame.class.getName());

    private PatientsPanel patientsPanel;
    private PrescriptionsPanel prescriptionsPanel;
    private DoctorsOrderPanel doctorsOrderPanel;
    private javax.swing.JPanel activePanel;
    public DoctorFrame() {

        initComponents();
        username.setText(DataStore.currentUserName);
        searchField.setVisible(false);
        searchBtn.setVisible(false);
    }

    
    /**
     * Creates new form DoctorFrame
     */
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchBtn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        patientBtn = new javax.swing.JButton();
        prescriptionsBtn = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        ordersBtn = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();

        searchBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/epharmacysystem/ui/dashboard/search-interface-symbol.png"))); // NOI18N
        searchBtn1.setText("Search");
        searchBtn1.addActionListener(this::searchBtn1ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DOCTOR DASHBOARD");

        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        patientBtn.setText("Patients' Record");
        patientBtn.addActionListener(this::patientBtnActionPerformed);

        prescriptionsBtn.setText("Prescriptions ");
        prescriptionsBtn.addActionListener(this::prescriptionsBtnActionPerformed);

        username.setText("Dr. (name)");

        ordersBtn.setText("Order Status");
        ordersBtn.addActionListener(this::ordersBtnActionPerformed);

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 247, Short.MAX_VALUE)
        );

        searchField.setText("Search...");
        searchField.addActionListener(this::searchFieldActionPerformed);

        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/epharmacysystem/ui/dashboard/search-interface-symbol.png"))); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(this::searchBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(username)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(patientBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prescriptionsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                        .addComponent(ordersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ordersBtn, patientBtn, prescriptionsBtn, searchBtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnLogout)
                    .addComponent(username))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientBtn)
                    .addComponent(prescriptionsBtn)
                    .addComponent(ordersBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
          new LoginFrame().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void patientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientBtnActionPerformed

    patientsPanel = new PatientsPanel();

    contentPanel.removeAll();
    contentPanel.setLayout(new java.awt.BorderLayout());
    contentPanel.add(patientsPanel);
    
    contentPanel.revalidate();
    contentPanel.repaint();
    
    
    activePanel = patientsPanel;
    searchField.setVisible(true);
    searchField.setText("Search for patients...");
    searchBtn.setVisible(true);
    this.pack();
    }//GEN-LAST:event_patientBtnActionPerformed

    private void prescriptionsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prescriptionsBtnActionPerformed
        // TODO add your handling code here:
    prescriptionsPanel = new PrescriptionsPanel();

    contentPanel.removeAll();
    contentPanel.setLayout(new java.awt.BorderLayout());
    contentPanel.add(prescriptionsPanel);

    contentPanel.revalidate();
    contentPanel.repaint();

    activePanel = prescriptionsPanel;
     searchField.setVisible(true);
    searchField.setText("Search for prescriptions...");
    searchBtn.setVisible(true);
    this.pack();
    }//GEN-LAST:event_prescriptionsBtnActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
    String text = searchField.getText();

    if (activePanel instanceof PatientsPanel) {
        ((PatientsPanel) activePanel).filterTable(text);
    } 
    else if(activePanel instanceof PrescriptionsPanel) {
        ((PrescriptionsPanel) activePanel).filterTable(text);
    } 
    else if(activePanel instanceof DoctorsOrderPanel) {
        ((DoctorsOrderPanel) activePanel).filterTable(text);
    } 
    }//GEN-LAST:event_searchBtnActionPerformed

    private void searchBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtn1ActionPerformed
      
        
    }//GEN-LAST:event_searchBtn1ActionPerformed

    private void ordersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersBtnActionPerformed
    doctorsOrderPanel = new DoctorsOrderPanel();

    contentPanel.removeAll();
    contentPanel.setLayout(new java.awt.BorderLayout());
    contentPanel.add(doctorsOrderPanel);

    contentPanel.revalidate();
    contentPanel.repaint();

    activePanel = doctorsOrderPanel;
    searchField.setVisible(true);
    searchField.setText("Search for prescriptions...");
    searchBtn.setVisible(true);
    this.pack();
    }//GEN-LAST:event_ordersBtnActionPerformed

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {

    java.awt.EventQueue.invokeLater(() -> {
        new DoctorFrame().setVisible(true);
    });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton ordersBtn;
    private javax.swing.JButton patientBtn;
    private javax.swing.JButton prescriptionsBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton searchBtn1;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
