/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package epharmacysystem.ui.dashboard;

import epharmacysystem.data.DataStore;
import epharmacysystem.ui.auth.LoginFrame;
import epharmacysystem.ui.panels.PharmacistsMedicinesPanel;
import epharmacysystem.ui.panels.PharmacistsOrdersPanel;
import epharmacysystem.ui.panels.PharmacistsPrescriptionsPanel;

/**
 *
 * @author Zid
 */
public class PharmacistFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PharmacistFrame.class.getName());
    private PharmacistsPrescriptionsPanel pharmacistsPrescriptionsPanel;
       private PharmacistsMedicinesPanel pharmacistsMedicinesPanel;
       private PharmacistsOrdersPanel pharmacistsOrdersPanel;
    private javax.swing.JPanel activePanel;
    /**
     * Creates new form PharmacistFrame
     */
    public PharmacistFrame() {
        initComponents();
        pack();
        setMinimumSize(new java.awt.Dimension(900, 500));
        setLocationRelativeTo(null);
        username.setText(DataStore.currentUserName);
        searchField.setVisible(false);
        searchBtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        prescriptionsPanel = new javax.swing.JButton();
        ordersPanel = new javax.swing.JButton();
        medicinesPanel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pharmacist's Dashboard");

        jLabel1.setFont(new java.awt.Font("Inter 18pt SemiBold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Pharmacist's Dashboard");

        btnLogout.setForeground(new java.awt.Color(255, 51, 51));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/epharmacysystem/ui/dashboard/search-interface-symbol.png"))); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(this::searchBtnActionPerformed);

        searchField.setText("Search...");
        searchField.addActionListener(this::searchFieldActionPerformed);

        username.setFont(new java.awt.Font("Inter 18pt SemiBold", 0, 12)); // NOI18N
        username.setText("Dr. (name)");

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 314, Short.MAX_VALUE)
        );

        prescriptionsPanel.setText("Prescriptions");
        prescriptionsPanel.addActionListener(this::prescriptionsPanelActionPerformed);

        ordersPanel.setText("Orders");
        ordersPanel.addActionListener(this::ordersPanelActionPerformed);

        medicinesPanel.setText("Medicines");
        medicinesPanel.addActionListener(this::medicinesPanelActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(prescriptionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(medicinesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ordersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(searchField))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                        .addComponent(username)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {medicinesPanel, ordersPanel, prescriptionsPanel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnLogout)
                    .addComponent(username))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(prescriptionsPanel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ordersPanel)
                            .addComponent(medicinesPanel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {medicinesPanel, ordersPanel, prescriptionsPanel});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed

        this.dispose();
         new LoginFrame().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        String text = searchField.getText();
        
       if (activePanel instanceof PharmacistsPrescriptionsPanel) {
        ((PharmacistsPrescriptionsPanel) activePanel).filterTable(text);
    } 
       else if( activePanel instanceof PharmacistsMedicinesPanel){
           ((PharmacistsMedicinesPanel) activePanel).filterTable(text);
       }
       else if( activePanel instanceof PharmacistsOrdersPanel){
           ((PharmacistsOrdersPanel) activePanel).filterTable(text);
       }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void prescriptionsPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prescriptionsPanelActionPerformed
    pharmacistsPrescriptionsPanel = new PharmacistsPrescriptionsPanel();
        

    contentPanel.removeAll();
    contentPanel.setLayout(new java.awt.BorderLayout());
    contentPanel.add(pharmacistsPrescriptionsPanel);
    
    contentPanel.revalidate();
    contentPanel.repaint();
    
    
    activePanel = pharmacistsPrescriptionsPanel;
    searchField.setVisible(true);
    searchField.setText("Search for patients...");
    searchBtn.setVisible(true);
    this.pack();
    }//GEN-LAST:event_prescriptionsPanelActionPerformed

    private void medicinesPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicinesPanelActionPerformed
   pharmacistsMedicinesPanel = new PharmacistsMedicinesPanel();
        

    contentPanel.removeAll();
    contentPanel.setLayout(new java.awt.BorderLayout());
    contentPanel.add(pharmacistsMedicinesPanel);
    
    contentPanel.revalidate();
    contentPanel.repaint();
    
    
    activePanel = pharmacistsMedicinesPanel;
    searchField.setVisible(true);
    searchField.setText("Search for medicines...");
    searchBtn.setVisible(true);
    this.pack();
    }//GEN-LAST:event_medicinesPanelActionPerformed

    private void ordersPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersPanelActionPerformed
    pharmacistsOrdersPanel = new PharmacistsOrdersPanel();
        

    contentPanel.removeAll();
    contentPanel.setLayout(new java.awt.BorderLayout());
    contentPanel.add( pharmacistsOrdersPanel);
    
    contentPanel.revalidate();
    contentPanel.repaint();
    
    
    activePanel =  pharmacistsOrdersPanel;
    searchField.setVisible(true);
    searchField.setText("Search for medicines...");
    searchBtn.setVisible(true);
    this.pack();
    }//GEN-LAST:event_ordersPanelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PharmacistFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton medicinesPanel;
    private javax.swing.JButton ordersPanel;
    private javax.swing.JButton prescriptionsPanel;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
