/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package epharmacysystem.ui.panels;

import epharmacysystem.data.DataStore;
import epharmacysystem.ui.dialogs.AddUserDialog;
import epharmacysystem.ui.dialogs.ChangePasswordDialog;
import epharmacysystem.ui.dialogs.EditPatientDialog;
import epharmacysystem.ui.dialogs.EditUserDialog;


/**
 *
 * @author Zid
 */
public class AdminUsersPanel extends javax.swing.JPanel {
  
    
    /**
     * Creates new form PatientsPanel
     */
    public AdminUsersPanel() {
        initComponents();
        loadUsers();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        addPatientBtn = new javax.swing.JButton();
        editPatientBtn = new javax.swing.JButton();
        deleteUserBtn = new javax.swing.JButton();
        changePasswordBtn = new javax.swing.JButton();

        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "User ID", "Username", "Role", "Full Name"
            }
        ));
        usersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(usersTable);

        addPatientBtn.setText("Add User");
        addPatientBtn.addActionListener(this::addPatientBtnActionPerformed);

        editPatientBtn.setText("Edit User");
        editPatientBtn.addActionListener(this::editPatientBtnActionPerformed);

        deleteUserBtn.setText("Delete User");
        deleteUserBtn.addActionListener(this::deleteUserBtnActionPerformed);

        changePasswordBtn.setText("Change User Password");
        changePasswordBtn.addActionListener(this::changePasswordBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addPatientBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editPatientBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteUserBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(changePasswordBtn))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPatientBtn)
                    .addComponent(editPatientBtn)
                    .addComponent(deleteUserBtn)
                    .addComponent(changePasswordBtn))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addPatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientBtnActionPerformed
        AddUserDialog dialog = new AddUserDialog(
        (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this),
        true, DataStore.instance
    );
    
    dialog.setLocationRelativeTo(this); 
    dialog.setVisible(true);
    loadUsers(); // refresh table
    }//GEN-LAST:event_addPatientBtnActionPerformed

    private void usersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersTableMouseClicked
       
      
    }//GEN-LAST:event_usersTableMouseClicked

    private void editPatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPatientBtnActionPerformed
        
    int selectedRow = usersTable.getSelectedRow();

    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Select a patient first!");
        return;
    }

    int modelRow = usersTable.convertRowIndexToModel(selectedRow);
    
    String userId = usersTable.getModel().getValueAt(modelRow, 0).toString();
    
    EditUserDialog dialog = new EditUserDialog(
        (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this),
        true,
        DataStore.instance,
        userId
    );

    dialog.setLocationRelativeTo(this); 
    dialog.setVisible(true);
    loadUsers();

    }//GEN-LAST:event_editPatientBtnActionPerformed

    private void deleteUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserBtnActionPerformed

        int row = usersTable.getSelectedRow();

    if (row == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a user to delete!");
        return;
    }

    int modelRow = usersTable.convertRowIndexToModel(row);
    
    // Get the User ID and Role from the table before deleting
    // Assuming Column 0 is User ID and Column 3 is Role
    String userIdToDelete = usersTable.getModel().getValueAt(modelRow, 0).toString();
    String role = usersTable.getModel().getValueAt(modelRow, 3).toString();

    // Prevent Admin from deleting themselves (Safety Check)
    // Assuming 'currentUser' is the ID of the person logged in
    // if (userIdToDelete.equals(currentUser)) { 
    //    javax.swing.JOptionPane.showMessageDialog(this, "You cannot delete your own account!");
    //    return;
    // }

    int confirm = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to delete user " + userIdToDelete + "?\nThis action cannot be undone.",
        "Confirm Deletion",
        javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (confirm != javax.swing.JOptionPane.YES_OPTION) return;

    // 1. DELETE FROM USERS ARRAY (The Login Account)
    for (int i = 0; i < DataStore.userCount; i++) {
        if (DataStore.users[i][0].equals(userIdToDelete)) {
            // Shift users array left
            for (int j = i; j < DataStore.userCount - 1; j++) {
                DataStore.users[j] = DataStore.users[j + 1];
            }
            DataStore.users[DataStore.userCount - 1] = null; // Clear last reference
            DataStore.userCount--;
            break;
        }
    }

    // 2. IF PATIENT, DELETE FROM PATIENTS ARRAY (The Medical Record)
    if (role.equalsIgnoreCase(DataStore.ROLE_PATIENT)) {
        for (int i = 0; i < DataStore.patientCount; i++) {
            // Index 6 in patients array is the linked UserID
            if (DataStore.patients[i][6].equals(userIdToDelete)) {
                // Shift patients array left
                for (int j = i; j < DataStore.patientCount - 1; j++) {
                    DataStore.patients[j] = DataStore.patients[j + 1];
                }
                DataStore.patients[DataStore.patientCount - 1] = null;
                DataStore.patientCount--;
                break;
            }
        }
    }

    // 3. Refresh UI
    loadUsers();
    javax.swing.JOptionPane.showMessageDialog(this, "User and associated records deleted.");
    }//GEN-LAST:event_deleteUserBtnActionPerformed

    private void changePasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordBtnActionPerformed
        int selectedRow = usersTable.getSelectedRow();

    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Select a patient first!");
        return;
    }

    int modelRow = usersTable.convertRowIndexToModel(selectedRow);
    
    String userId = usersTable.getModel().getValueAt(modelRow, 0).toString();
    
    ChangePasswordDialog dialog = new ChangePasswordDialog(
        (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this),
        true,
        DataStore.instance,
        userId
    );

    dialog.setLocationRelativeTo(this); 
    dialog.setVisible(true);
    loadUsers();
    }//GEN-LAST:event_changePasswordBtnActionPerformed

private void loadUsers() {
    
    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) usersTable.getModel();

    model.setRowCount(0); 
    


    for (int i = 0; i < DataStore.userCount; i++) {
        model.addRow(new Object[]{
            DataStore.users[i][0], // ID
            DataStore.users[i][1], // username
            DataStore.users[i][3], // Role
            DataStore.users[i][4], // Fullname
        });
    }
}

public void filterTable(String text) {

    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) usersTable.getModel();

    javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter =
        new javax.swing.table.TableRowSorter<>(model);

    usersTable.setRowSorter(sorter);

    sorter.setRowFilter(
    javax.swing.RowFilter.regexFilter("(?i)^" + java.util.regex.Pattern.quote(text))
);
    
    
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPatientBtn;
    private javax.swing.JButton changePasswordBtn;
    private javax.swing.JButton deleteUserBtn;
    private javax.swing.JButton editPatientBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables
}

