/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package epharmacysystem.ui.panels;

import epharmacysystem.data.DataStore;
import epharmacysystem.ui.dialogs.AddPatientDialog;
import epharmacysystem.ui.dialogs.DoctorCreateOrderDialog;/**/
import epharmacysystem.ui.dialogs.EditOrderStatusDialog;
import epharmacysystem.ui.dialogs.ViewOrderDialog;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Zid
 */
public class AdminOrdersPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorsOrderPanel
     */
    public AdminOrdersPanel() {
        initComponents();
        loadOrders();
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        adminOrderTbl = new javax.swing.JTable();
        btnUpdateStatusOrder = new javax.swing.JButton();
        btnViewOrder = new javax.swing.JButton();
        deleteOrderBtn = new javax.swing.JButton();

        adminOrderTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Patient", "Medicine", "Quantity", "Total Price", "Ward", "Status", "Date"
            }
        ));
        jScrollPane1.setViewportView(adminOrderTbl);

        btnUpdateStatusOrder.setText("Update Order Status");
        btnUpdateStatusOrder.addActionListener(this::btnUpdateStatusOrderActionPerformed);

        btnViewOrder.setText("View Order");
        btnViewOrder.addActionListener(this::btnViewOrderActionPerformed);

        deleteOrderBtn.setText("Delete Order");
        deleteOrderBtn.addActionListener(this::deleteOrderBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUpdateStatusOrder)
                        .addGap(18, 18, 18)
                        .addComponent(deleteOrderBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 488, Short.MAX_VALUE)
                        .addComponent(btnViewOrder))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateStatusOrder)
                    .addComponent(btnViewOrder)
                    .addComponent(deleteOrderBtn))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    public void filterTable(String text) {

    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) adminOrderTbl.getModel();

    javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter =
        new javax.swing.table.TableRowSorter<>(model);

    adminOrderTbl.setRowSorter(sorter);

    sorter.setRowFilter(
    javax.swing.RowFilter.regexFilter("(?i)^" + java.util.regex.Pattern.quote(text))
);
}
    private void btnUpdateStatusOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStatusOrderActionPerformed
       int row = adminOrderTbl.getSelectedRow();
        
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select an order to update!");
            return;
        }
        
        int modelRow = adminOrderTbl.convertRowIndexToModel(row);
        String orderId = adminOrderTbl.getModel().getValueAt(modelRow, 0).toString();

        // Fixed constructor call: Removed undefined 'ds' and passed 'orderId'
        EditOrderStatusDialog dialog = new EditOrderStatusDialog(
            (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this),
            true, 
     null,
            orderId
        );
        
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        
        loadOrders(); 
    }//GEN-LAST:event_btnUpdateStatusOrderActionPerformed

    private void btnViewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrderActionPerformed
        int row = adminOrderTbl.getSelectedRow();
        
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a prescription first!");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) adminOrderTbl.getModel();
        
        String orderId = model.getValueAt(row, 0).toString();
        
        ViewOrderDialog dialog =
        new ViewOrderDialog(
        (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this),
        true,orderId
        );
       dialog.setLocationRelativeTo(this); 
        dialog.setVisible(true);    
    }//GEN-LAST:event_btnViewOrderActionPerformed

    private void deleteOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteOrderBtnActionPerformed
     int row = adminOrderTbl.getSelectedRow();
    
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select an order to delete!");
        return;
    }

    // 1. Get the Order ID from the table (handling potential sorting/filtering)
    int modelRow = adminOrderTbl.convertRowIndexToModel(row);
    String orderId = adminOrderTbl.getModel().getValueAt(modelRow, 0).toString();

    // 2. Confirm Deletion
    int confirm = JOptionPane.showConfirmDialog(this, 
        "Are you sure you want to delete Order " + orderId + "?\nThis will permanently remove the record.", 
        "Confirm Deletion", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

    if (confirm == JOptionPane.YES_OPTION) {
        int orderIndex = -1;

        // 3. Find the order index in DataStore
        for (int i = 0; i < DataStore.orderCount; i++) {
            if (DataStore.orders[i][0].equals(orderId)) {
                orderIndex = i;
                break;
            }
        }

        if (orderIndex != -1) {
            String status = DataStore.orders[orderIndex][5];
            String medicineName = DataStore.orders[orderIndex][3];
            int qtyToRestore = Integer.parseInt(DataStore.orders[orderIndex][4]);

            // 4. STOCK RESTORATION
            // If the order was Approved or Delivered, we must put the stock back
            if (status.equals(DataStore.ORDER_APPROVED) || status.equals(DataStore.ORDER_DELIVERED)) {
                for (int m = 0; m < DataStore.medicineCount; m++) {
                    if (DataStore.medicines[m][1].equals(medicineName)) {
                        int currentStock = Integer.parseInt(DataStore.medicines[m][2]);
                        DataStore.medicines[m][2] = String.valueOf(currentStock + qtyToRestore);
                        break;
                    }
                }
            }

            // 5. REMOVE FROM ARRAY (Shift elements to the left)
            for (int j = orderIndex; j < DataStore.orderCount - 1; j++) {
                DataStore.orders[j] = DataStore.orders[j + 1];
            }
            
            // Clean up the last index and decrement count
            DataStore.orders[DataStore.orderCount - 1] = null;
            DataStore.orderCount--;

            JOptionPane.showMessageDialog(this, "Order deleted successfully. Stock has been adjusted.");
            
            // 6. Refresh UI
            loadOrders(); 
        }
    }
    }//GEN-LAST:event_deleteOrderBtnActionPerformed

private void loadOrders() {

    javax.swing.table.DefaultTableModel model =
    (javax.swing.table.DefaultTableModel) adminOrderTbl.getModel();
    model.setRowCount(0); 
 
   

    for (int i = 0; i < DataStore.orderCount; i++) {
       
        
        String orderId = DataStore.orders[i][0];
        String patientId = DataStore.orders[i][1];
        String medicine = DataStore.orders[i][3];
        String quantity = DataStore.orders[i][4];
        String status = DataStore.orders[i][5];
        String date = DataStore.orders[i][6];
        String total = DataStore.orders[i][7];
        String ward = DataStore.orders[i][9];

        model.addRow(new Object[]{
            orderId,
            patientId,
            medicine,
            quantity,
            total,
            ward,
            status,
            date
        });
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable adminOrderTbl;
    private javax.swing.JButton btnUpdateStatusOrder;
    private javax.swing.JButton btnViewOrder;
    private javax.swing.JButton deleteOrderBtn;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
