/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package epharmacysystem.ui.panels;

import epharmacysystem.data.DataStore;
import epharmacysystem.ui.dialogs.AddPatientDialog;
import epharmacysystem.ui.dialogs.DoctorCreateOrderDialog;
import epharmacysystem.ui.dialogs.ViewOrdersDialog;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Zid
 */
public class DoctorsOrdersPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorsOrderPanel
     */
    public DoctorsOrdersPanel() {
        initComponents();
        loadOrders();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        doctorsOrderTbl = new javax.swing.JTable();
        btnCreateOrder = new javax.swing.JButton();
        btnViewOrder = new javax.swing.JButton();

        doctorsOrderTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Patient", "Medicine", "Quantity", "Total Price", "Status", "Date"
            }
        ));
        jScrollPane1.setViewportView(doctorsOrderTbl);

        btnCreateOrder.setText("Create Order");
        btnCreateOrder.addActionListener(this::btnCreateOrderActionPerformed);

        btnViewOrder.setText("View Order");
        btnViewOrder.addActionListener(this::btnViewOrderActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreateOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnViewOrder)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateOrder)
                    .addComponent(btnViewOrder))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateOrderActionPerformed
        // TODO add your handling code here:
    DoctorCreateOrderDialog dialog = new DoctorCreateOrderDialog(
    (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this),
    true
    );
    dialog.setLocationRelativeTo(this);
    dialog.setVisible(true);
    
    loadOrders(); 
    }//GEN-LAST:event_btnCreateOrderActionPerformed

    private void btnViewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrderActionPerformed
        int row = doctorsOrderTbl.getSelectedRow();
        
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a prescription first!");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) doctorsOrderTbl.getModel();
        
        String orderId = model.getValueAt(row, 0).toString();
        
        ViewOrdersDialog dialog =
        new ViewOrdersDialog(
        (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this),
        true,orderId
        );
       dialog.setLocationRelativeTo(this); 
        dialog.setVisible(true);    
    }//GEN-LAST:event_btnViewOrderActionPerformed

private void loadOrders() {

    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) doctorsOrderTbl.getModel();
     
    model.setRowCount(0); 
    
    String currentDoctorId = DataStore.currentUserId;
   

    for (int i = 0; i < DataStore.orderCount; i++) {
        String doctorId = DataStore.orders[i][8];

        if (doctorId == null || !doctorId.equals(currentDoctorId)) {
            continue;
        }
        
        String orderId = DataStore.orders[i][0];
        String patientId = DataStore.orders[i][1];
        String medicine = DataStore.orders[i][3];
        String quantity = DataStore.orders[i][4];
        String status = DataStore.orders[i][5];
        String date = DataStore.orders[i][6];
        String total = DataStore.orders[i][7];

        model.addRow(new Object[]{
            orderId,
            patientId,
            medicine,
            quantity,
            total,
            status,
            date
        });
    }
}

public void filterTable(String text) {

    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) doctorsOrderTbl.getModel();

    javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter =
        new javax.swing.table.TableRowSorter<>(model);

    doctorsOrderTbl.setRowSorter(sorter);

    sorter.setRowFilter(
    javax.swing.RowFilter.regexFilter("(?i)^" + java.util.regex.Pattern.quote(text))
        );
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateOrder;
    private javax.swing.JButton btnViewOrder;
    private javax.swing.JTable doctorsOrderTbl;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
