package epharmacysystem.ui.panels;

import epharmacysystem.ui.dialogs.ViewOrdersDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Zid
 */
public class MyOrdersPanel extends javax.swing.JPanel {

    /**
     * Creates new form MyOrdersPanel
     */
    public MyOrdersPanel() {
        initComponents();
        loadMyOrders();
    }

    
    private void loadMyOrders() {

    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) myOrdersTbl.getModel();
    model.setRowCount(0); 

    String currentPatientId = null;
    
    for (int i = 0; i < epharmacysystem.data.DataStore.patientCount; i++) {
        if (epharmacysystem.data.DataStore.patients[i][6]
                .equals(epharmacysystem.data.DataStore.currentUserId)) {

            currentPatientId = epharmacysystem.data.DataStore.patients[i][0];
            break;
        }
    }
    
    if (currentPatientId == null) return;
    
    for (int i = 0; i < epharmacysystem.data.DataStore.orderCount; i++) {
        
        if (!epharmacysystem.data.DataStore.orders[i][1]
                .equals(currentPatientId)) {
            continue; // skip others
        }
        
        String orderId = epharmacysystem.data.DataStore.orders[i][0];
        String medicine = epharmacysystem.data.DataStore.orders[i][3];
        String quantity = epharmacysystem.data.DataStore.orders[i][4];
        String status = epharmacysystem.data.DataStore.orders[i][5];
        String date = epharmacysystem.data.DataStore.orders[i][6];
        String total = epharmacysystem.data.DataStore.orders[i][7];

        model.addRow(new Object[]{
            orderId,
            medicine,
            quantity,
            total,
            status,
            date
        });
    }
}

public void filterTable(String text) {

    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) myOrdersTbl.getModel();

    javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter =
        new javax.swing.table.TableRowSorter<>(model);

    myOrdersTbl.setRowSorter(sorter);

    sorter.setRowFilter(
    javax.swing.RowFilter.regexFilter("(?i)^" + java.util.regex.Pattern.quote(text))
        );
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        myOrdersTbl = new javax.swing.JTable();
        btnViewOrder = new javax.swing.JButton();

        jScrollPane1.setPreferredSize(new java.awt.Dimension(0, 0));

        myOrdersTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Medicine", "Quantity", "Total Price", "Status", "Date"
            }
        ));
        jScrollPane1.setViewportView(myOrdersTbl);

        btnViewOrder.setText("View Order");
        btnViewOrder.addActionListener(this::btnViewOrderActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnViewOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 404, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewOrder))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrderActionPerformed
 int row = myOrdersTbl.getSelectedRow();
        
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a prescription first!");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) myOrdersTbl.getModel();
        
        String orderId = model.getValueAt(row, 0).toString();
        
        ViewOrdersDialog dialog =
        new ViewOrdersDialog(
        (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this),
        true,orderId
        );
       
        dialog.setVisible(true);    
    }//GEN-LAST:event_btnViewOrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewOrder;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable myOrdersTbl;
    // End of variables declaration//GEN-END:variables
}
