/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package epharmacysystem.ui.panels;

import epharmacysystem.data.DataStore;
import epharmacysystem.ui.dialogs.ViewPrescriptionsDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Zid
 */
public class MyPrescriptionsPanel extends javax.swing.JPanel {

    /**
     * Creates new form MyPrescriptions
     */
    public MyPrescriptionsPanel() {
        initComponents();
        loadMyPrescriptions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        myPrescriptionsTbl = new javax.swing.JTable();
        btnViewPrescription = new javax.swing.JButton();

        myPrescriptionsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Prescription ID", "Medicine Name", "Dosage", "Quantity", "Instructions", "Date", "Status"
            }
        ));
        jScrollPane1.setViewportView(myPrescriptionsTbl);

        btnViewPrescription.setText("View Prescription");
        btnViewPrescription.addActionListener(this::btnViewPrescriptionActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnViewPrescription, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewPrescription)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPrescriptionActionPerformed
        
        int row = myPrescriptionsTbl.getSelectedRow();
        
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a prescription first!");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) myPrescriptionsTbl.getModel();
        
        String prescriptionId = model.getValueAt(row, 0).toString();
        
        ViewPrescriptionsDialog dialog =
        new ViewPrescriptionsDialog(
        (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this),
        true,prescriptionId
        );
       
        dialog.setVisible(true);    
    }//GEN-LAST:event_btnViewPrescriptionActionPerformed
private void loadMyPrescriptions() {

    DefaultTableModel model = (DefaultTableModel) myPrescriptionsTbl.getModel();
    model.setRowCount(0); // clear table

    String currentUserId = DataStore.currentUserId;

    // 1. Find patient ID linked to this user
    String patientId = null;

    for (int i = 0; i < DataStore.patientCount; i++) {
        if (DataStore.patients[i][6].equals(currentUserId)) {
            patientId = DataStore.patients[i][0]; // P001, P002
            break;
        }
    }

    // 2. If no patient found, stop
    if (patientId == null) return;

    // 3. Filter prescriptions
    for (int i = 0; i < DataStore.prescriptionCount; i++) {

        if (DataStore.prescriptions[i][1].equals(patientId)) {

            model.addRow(new Object[]{
                DataStore.prescriptions[i][0], // RX ID
                DataStore.prescriptions[i][3], // Medicine
                DataStore.prescriptions[i][4], // Dosage
                DataStore.prescriptions[i][5], // Quantity
                DataStore.prescriptions[i][8], // Instructions
                DataStore.prescriptions[i][6], // Date
                DataStore.prescriptions[i][7]  // Status
            });
        }
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewPrescription;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable myPrescriptionsTbl;
    // End of variables declaration//GEN-END:variables
}
