/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package epharmacysystem.ui.panels;

import epharmacysystem.data.DataStore;
import epharmacysystem.ui.dialogs.AddMedicineDialog;
import epharmacysystem.ui.dialogs.AddPatientDialog;
import epharmacysystem.ui.dialogs.EditMedicineDialog;
import epharmacysystem.ui.dialogs.EditPatientDialog;


/**
 *
 * @author Zid
 */
public class PharmacistsMedicinesPanel extends javax.swing.JPanel {

    
    /**
     * Creates new form PatientsPanel
     */
    public PharmacistsMedicinesPanel() {
        initComponents();
        loadMedicines();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        medicinesTbl = new javax.swing.JTable();
        addPatientBtn = new javax.swing.JButton();
        editPatientBtn = new javax.swing.JButton();
        deletePatientBtn = new javax.swing.JButton();

        medicinesTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Stocks", "Unit price", "Expiry Date", "Company", "Category"
            }
        ));
        medicinesTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medicinesTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(medicinesTbl);

        addPatientBtn.setText("Add Medicine");
        addPatientBtn.addActionListener(this::addPatientBtnActionPerformed);

        editPatientBtn.setText("Edit Medicine");
        editPatientBtn.addActionListener(this::editPatientBtnActionPerformed);

        deletePatientBtn.setText("Delete Medicine");
        deletePatientBtn.addActionListener(this::deletePatientBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addPatientBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editPatientBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deletePatientBtn)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPatientBtn)
                    .addComponent(editPatientBtn)
                    .addComponent(deletePatientBtn))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addPatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientBtnActionPerformed
        AddMedicineDialog dialog = new AddMedicineDialog(
        (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this),
        true, DataStore.instance
    );
    
    dialog.setLocationRelativeTo(this); 
    dialog.setVisible(true);
    loadMedicines(); 
    }//GEN-LAST:event_addPatientBtnActionPerformed

    private void medicinesTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medicinesTblMouseClicked
       
      
    }//GEN-LAST:event_medicinesTblMouseClicked

    private void editPatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPatientBtnActionPerformed
        
    int selectedRow = medicinesTbl.getSelectedRow();

    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Select a medicine first!");
        return;
    }

    int modelRow = medicinesTbl.convertRowIndexToModel(selectedRow);
    
    String medicineId = medicinesTbl.getModel().getValueAt(modelRow, 0).toString();
    
    EditMedicineDialog dialog = new EditMedicineDialog(
        (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this),
        true,
        DataStore.instance,
        medicineId
    );

    dialog.setLocationRelativeTo(this); 
    dialog.setVisible(true);
    loadMedicines();

    }//GEN-LAST:event_editPatientBtnActionPerformed

    private void deletePatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePatientBtnActionPerformed

        int row = medicinesTbl.getSelectedRow();

        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select a medicine first!");
            return;
        }

        int modelRow = medicinesTbl.convertRowIndexToModel(row);

        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete this patient?",
            "Confirm Delete",
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirm != javax.swing.JOptionPane.YES_OPTION) return;

        // shift array left
        for (int i = modelRow; i < DataStore.patientCount - 1; i++) {
            DataStore.patients[i] = DataStore.patients[i + 1];
        }

        DataStore.patientCount--;

        loadMedicines();

    }//GEN-LAST:event_deletePatientBtnActionPerformed

private void loadMedicines() {
    
    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) medicinesTbl.getModel();

    model.setRowCount(0); 
    
    

    for (int i = 0; i < DataStore.medicineCount; i++) {
        


        model.addRow(new Object[]{
            DataStore.medicines[i][0], // Medicine ID
            DataStore.medicines[i][1], // Medicine Name
            DataStore.medicines[i][2], // Medicine Stocks
            DataStore.medicines[i][3], // Medicine Unit Price
            DataStore.medicines[i][4], // Medicine Expirty Date
            DataStore.medicines[i][5],  // Medicine Company
            DataStore.medicines[i][6],  // Medicine Category
        });
    }
}

public void filterTable(String text) {

    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) medicinesTbl.getModel();

    javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter =
        new javax.swing.table.TableRowSorter<>(model);

    medicinesTbl.setRowSorter(sorter);

    sorter.setRowFilter(
    javax.swing.RowFilter.regexFilter("(?i)^" + java.util.regex.Pattern.quote(text))
);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPatientBtn;
    private javax.swing.JButton deletePatientBtn;
    private javax.swing.JButton editPatientBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable medicinesTbl;
    // End of variables declaration//GEN-END:variables
}

