package epharmacysystem.ui.panels;

import epharmacysystem.data.DataStore;
import epharmacysystem.ui.dialogs.AddPrescriptionDialog;
import epharmacysystem.ui.dialogs.EditPrescriptionDialog;
import epharmacysystem.ui.dialogs.ViewPrescriptionsDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Zid
 */
public class PrescriptionsPanel extends javax.swing.JPanel {
    
    private TableRowSorter<DefaultTableModel> sorter;
    public PrescriptionsPanel() {
    initComponents();
    loadPrescriptions();

    }

    
    
    /* PrescriptionsPanel(DataStore sharedDataStore) {
    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        prescriptionsTable = new javax.swing.JTable();
        btnAddPrescription = new javax.swing.JButton();
        btnEditPrescription = new javax.swing.JButton();
        btnDeletePrescription = new javax.swing.JButton();
        btnViewPrescription = new javax.swing.JButton();

        prescriptionsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Patient ID", "Doctor ID", "Medicine Name", "Dosage", "Quantity", "Date", "Status", "Instructions"
            }
        ));
        jScrollPane1.setViewportView(prescriptionsTable);

        btnAddPrescription.setText("Add Prescription");
        btnAddPrescription.addActionListener(this::btnAddPrescriptionActionPerformed);

        btnEditPrescription.setText("Edit Prescription");
        btnEditPrescription.addActionListener(this::btnEditPrescriptionActionPerformed);

        btnDeletePrescription.setText("Delete Prescription");
        btnDeletePrescription.addActionListener(this::btnDeletePrescriptionActionPerformed);

        btnViewPrescription.setText("View Prescription");
        btnViewPrescription.addActionListener(this::btnViewPrescriptionActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnAddPrescription)
                .addGap(18, 18, 18)
                .addComponent(btnEditPrescription)
                .addGap(18, 18, 18)
                .addComponent(btnDeletePrescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViewPrescription)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddPrescription)
                    .addComponent(btnEditPrescription)
                    .addComponent(btnDeletePrescription)
                    .addComponent(btnViewPrescription))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPrescriptionActionPerformed
        // TODO add your handling code here:
         AddPrescriptionDialog dialog = new AddPrescriptionDialog(
        (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this),
        true
    );

    dialog.setLocationRelativeTo(this);
    dialog.setVisible(true);
    
    loadPrescriptions();
    }//GEN-LAST:event_btnAddPrescriptionActionPerformed

    private void btnEditPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPrescriptionActionPerformed
      int row = prescriptionsTable.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select a prescription first!");
            return;
        }

        int modelRow = prescriptionsTable.convertRowIndexToModel(row);

        // Pass ds and modelRow to keep it consistent with Patients pattern
        EditPrescriptionDialog dialog = new EditPrescriptionDialog(
            (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this),
            true,DataStore.instance, modelRow
        );
        dialog.setVisible(true);
        loadPrescriptions();
    



    }//GEN-LAST:event_btnEditPrescriptionActionPerformed

    private void btnDeletePrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePrescriptionActionPerformed
        int row = prescriptionsTable.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select a prescription first!");
            return;
        }

        int modelRow = prescriptionsTable.convertRowIndexToModel(row);
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Delete this prescription?", "Confirm", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            // Shift array left (same pattern as patients)
            for (int i = modelRow; i < DataStore.prescriptionCount - 1; i++) {
                DataStore.prescriptions[i] = DataStore.prescriptions[i + 1];
            }
            DataStore.prescriptionCount--;
            loadPrescriptions();
        }
    }//GEN-LAST:event_btnDeletePrescriptionActionPerformed

    private void btnViewPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPrescriptionActionPerformed
        // TODO add your handling code here:
        int viewRow = prescriptionsTable.getSelectedRow();
        
        if (viewRow == -1) {
            JOptionPane.showMessageDialog(this, "Select a prescription first!");
            return;
        }
        
         int modelRow = prescriptionsTable.convertRowIndexToModel(viewRow);
         
         String prescriptionId =
            prescriptionsTable.getModel()
            .getValueAt(modelRow, 0)
            .toString();
         
  ViewPrescriptionsDialog dialog =
        new ViewPrescriptionsDialog(
            (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this),
            true,
            prescriptionId
        );
       
        dialog.setVisible(true);        
    }//GEN-LAST:event_btnViewPrescriptionActionPerformed


    private void loadPrescriptions() {

    DefaultTableModel model = (DefaultTableModel) prescriptionsTable.getModel();

    model.setRowCount(0);

    for (int i = 0; i < DataStore.prescriptionCount; i++) {

        String patientId = DataStore.prescriptions[i][1];
        String doctorId = DataStore.prescriptions[i][2];

        String patientName = patientId;
        String doctorName = doctorId;

        // find patient name
        for (int j = 0; j < DataStore.patientCount; j++) {
            if (DataStore.patients[j][0].equals(patientId)) {
                patientName = DataStore.patients[j][1];
                break;
            }
        }

        // find doctor name
        for (int j = 0; j < DataStore.users.length; j++) {
            if (DataStore.users[j][0].equals(doctorId)) {
                doctorName = DataStore.users[j][4];
                break;
            }
        }

        model.addRow(new Object[]{
            DataStore.prescriptions[i][0], // ID
            patientName,
            doctorName,
            DataStore.prescriptions[i][3], // Medicine
            DataStore.prescriptions[i][4], // Dosage
            DataStore.prescriptions[i][5], // Quantity
            DataStore.prescriptions[i][6], // Date
            DataStore.prescriptions[i][7],  // Status 
     DataStore.prescriptions[i][8]  // Instructions
        });
    }
    if (sorter == null) {
        sorter = new TableRowSorter<>(model);
        prescriptionsTable.setRowSorter(sorter);
    }
}
   
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPrescription;
    private javax.swing.JButton btnDeletePrescription;
    private javax.swing.JButton btnEditPrescription;
    private javax.swing.JButton btnViewPrescription;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable prescriptionsTable;
    // End of variables declaration//GEN-END:variables

public void filterTable(String text) {

    if (sorter == null) return;

    if (text == null || text.trim().isEmpty()) {
        sorter.setRowFilter(null);
    } else {
        sorter.setRowFilter(
            RowFilter.regexFilter("(?i)" + java.util.regex.Pattern.quote(text))
        );
    }
}
}
