package epharmacysystem.ui.panels;

import epharmacysystem.data.DataStore;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Zid
 */
public class PrescriptionsPanel extends javax.swing.JPanel {
    private DataStore ds;
    public PrescriptionsPanel(DataStore ds) {
    this.ds = ds;
    initComponents();
    loadPrescriptions();

    DefaultTableModel model =(DefaultTableModel) prescriptionsTable.getModel();

    sorter = new TableRowSorter<>(model);
    prescriptionsTable.setRowSorter(sorter);
    }

    /* PrescriptionsPanel(DataStore sharedDataStore) {
    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        prescriptionsTable = new javax.swing.JTable();

        prescriptionsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Patient ID", "Doctor Name", "Medicine Name", "Dosage", "Quantity", "Date", "Status"
            }
        ));
        jScrollPane1.setViewportView(prescriptionsTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void loadPrescriptions() {

    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) prescriptionsTable.getModel();

    model.setRowCount(0); // clear table

    for (int i = 0; i < ds.prescriptionCount; i++) {
  
        model.addRow(new Object[]{
            ds.prescriptions[i][0], // ID
            ds.prescriptions[i][1], // Patient ID
            ds.prescriptions[i][2], // Doctor
            ds.prescriptions[i][3], // Medicine
            ds.prescriptions[i][4], // Dosage
            ds.prescriptions[i][5], // Quantity
            ds.prescriptions[i][6], // Date
            ds.prescriptions[i][7]  // Status
        });
    }
}
    private javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter;
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable prescriptionsTable;
    // End of variables declaration//GEN-END:variables

  public void filterTable(String text) {
    if (sorter == null) return;

    if (text == null || text.trim().isEmpty()) {
        sorter.setRowFilter(null);
    } else {
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
    }
}
}
