/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package epharmacysystem.ui.dialogs;

import epharmacysystem.data.DataStore;
import java.awt.Frame;
import javax.swing.JOptionPane;
/**
 *
 * @author Zid
 */
public class AdminEditPrescriptionDialog extends javax.swing.JDialog {
    private DataStore ds;  
    private String prescriptionId;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminEditPrescriptionDialog.class.getName());
     
    

    /**
     * Creates new form EditPrescriptionDialog
     */
    public AdminEditPrescriptionDialog(java.awt.Frame parent, boolean modal, DataStore ds, String prescriptionId) {
        super(parent, modal);
        this.ds = ds;
        this.prescriptionId = prescriptionId;
        initComponents();
        loadData();
    }

    private void loadData(){
       int rowIndex = -1;

    for (int i = 0; i < DataStore.prescriptionCount; i++) {
        if (DataStore.prescriptions[i][0].equals(prescriptionId)) {
            rowIndex = i;
            break;
        }
    }

    if (rowIndex == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Prescription not found!");
        this.dispose();
        return;
    }

    // ===== 1. GET DATA FROM ARRAY =====
    String patientId = ds.prescriptions[rowIndex][1];
    String doctorId = ds.prescriptions[rowIndex][2];
    String medicine = ds.prescriptions[rowIndex][3];
    String dosage = ds.prescriptions[rowIndex][4];
    String quantity = ds.prescriptions[rowIndex][5];
    String status = ds.prescriptions[rowIndex][7];
    String instructions = ds.prescriptions[rowIndex][8];

    // ===== 2. LOOK UP PATIENT NAME FOR DISPLAY =====
    String patientName = "Unknown Patient";
    for (int i = 0; i < DataStore.patientCount; i++) {
        if (DataStore.patients[i][0].equals(patientId)) {
            patientName = DataStore.patients[i][1];
            break;
        }
    }

    // ===== 3. FILL THE LABELS (UNEDITABLE) =====
    lblPatient.setText(patientId + " - " + patientName);
    lblMedicine.setText(medicine);
    lblDosage.setText(dosage);
    lblQuantity.setText(quantity);
    lblInstructions.setText(instructions);

    // ===== 4. LOAD STATUS COMBO BOX (EDITABLE) =====
    cmbRxStatus.removeAllItems();
    cmbRxStatus.addItem(DataStore.RX_PENDING);
    cmbRxStatus.addItem(DataStore.RX_ACTIVE);
    cmbRxStatus.addItem(DataStore.RX_FULFILLED);
    cmbRxStatus.addItem(DataStore.RX_CANCELLED);
    
    cmbRxStatus.setSelectedItem(status);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSavePrescription = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        cmbRxStatus = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        lblPatient = new javax.swing.JLabel();
        lblDosage = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        lblInstructions = new javax.swing.JLabel();
        lblMedicine = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Patient Name:");

        jLabel2.setText("Dosage: ");

        jLabel3.setText("Medicine: ");

        jLabel4.setText("Quantity:");

        jLabel5.setText("Instructions:");

        btnSavePrescription.setText("Save");
        btnSavePrescription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSavePrescriptionMouseClicked(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this::btnCancelActionPerformed);

        cmbRxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Active", "Fulfilled", "Cancelled" }));

        jLabel7.setText("Status:");

        lblPatient.setText("N/A");

        lblDosage.setText("N/A");

        lblQuantity.setText("0");

        lblInstructions.setText("N/A");

        lblMedicine.setText("N/A");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(69, 69, 69)
                        .addComponent(lblQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(btnSavePrescription, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblInstructions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDosage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMedicine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbRxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(lblPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel4, jLabel5});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblPatient))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblDosage))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblMedicine))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(lblQuantity))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblInstructions))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbRxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSavePrescription))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("EDIT PRESCRIPTION");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel6.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
  
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSavePrescriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSavePrescriptionMouseClicked

        int rowIndex = -1;

    for (int i = 0; i < DataStore.prescriptionCount; i++) {
        if (DataStore.prescriptions[i][0].equals(prescriptionId)) {
            rowIndex = i;
            break;
        }
    }

    if (rowIndex == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Prescription not found!");
        return;
    }

    // ===== SAVE ONLY THE STATUS =====
    String newStatus = cmbRxStatus.getSelectedItem().toString();
    ds.prescriptions[rowIndex][7] = newStatus;

    javax.swing.JOptionPane.showMessageDialog(this, "Status updated to: " + newStatus);
    dispose();
    }//GEN-LAST:event_btnSavePrescriptionMouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSavePrescription;
    private javax.swing.JComboBox<String> cmbRxStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDosage;
    private javax.swing.JLabel lblInstructions;
    private javax.swing.JLabel lblMedicine;
    private javax.swing.JLabel lblPatient;
    private javax.swing.JLabel lblQuantity;
    // End of variables declaration//GEN-END:variables

}
