/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package epharmacysystem.ui.dialogs;

import epharmacysystem.data.DataStore;

/**
 *
 * @author Zid
 */
public class DoctorCreateOrderDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DoctorCreateOrderDialog.class.getName());

    /**
     * Creates new form DoctorCreateOrder
     */
    public DoctorCreateOrderDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addDoctorOrderPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmbPrescription = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtOrderQuantity = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtUnitPrice = new javax.swing.JLabel();
        txtTotalPrice = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtMedicineName = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnPlaceOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setText("Prescription:");

        cmbPrescription.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPrescription.addActionListener(this::cmbPrescriptionActionPerformed);

        jLabel7.setText("Auto-calculated:");

        txtOrderQuantity.setText("orderQuantity");

        jLabel9.setText("Total Price:");

        txtUnitPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtUnitPrice.setText("unitPrice");

        txtTotalPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtTotalPrice.setText("totalPrice");

        jLabel18.setText("Unit Price:");

        jLabel19.setText("Order Quantity");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel19))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtOrderQuantity))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtOrderQuantity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtUnitPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTotalPrice)))
        );

        jLabel12.setText("AUTO-FILLED DETAILS");

        jLabel5.setText("Patient Name:");

        txtPatientName.setText("patientName");

        jLabel14.setText("Medicine:");

        txtMedicineName.setText("medicineName");

        jLabel16.setText("Rx Quantity:");

        txtQuantity.setText("rxQuantity");

        javax.swing.GroupLayout addDoctorOrderPanelLayout = new javax.swing.GroupLayout(addDoctorOrderPanel);
        addDoctorOrderPanel.setLayout(addDoctorOrderPanelLayout);
        addDoctorOrderPanelLayout.setHorizontalGroup(
            addDoctorOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDoctorOrderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addDoctorOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addDoctorOrderPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(cmbPrescription, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addDoctorOrderPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPatientName))
                    .addGroup(addDoctorOrderPanelLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMedicineName))
                    .addGroup(addDoctorOrderPanelLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtQuantity))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addDoctorOrderPanelLayout.setVerticalGroup(
            addDoctorOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDoctorOrderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addDoctorOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbPrescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(addDoctorOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPatientName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addDoctorOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtMedicineName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addDoctorOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtQuantity))
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CREATE NEW ORDER");

        btnCancel.setText("CANCEL");
        btnCancel.addActionListener(this::btnCancelActionPerformed);

        btnPlaceOrder.setText("PLACE ORDER");
        btnPlaceOrder.addActionListener(this::btnPlaceOrderActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addDoctorOrderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addDoctorOrderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnPlaceOrder))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        String selected = (String) cmbPrescription.getSelectedItem();
        if (selected == null) return;

        String rxId = selected.split(" - ")[0];

        for (int i = 0; i < DataStore.prescriptionCount; i++) {

            if (DataStore.prescriptions[i][0].equals(rxId)) {

                String patientId = DataStore.prescriptions[i][1];
                String medicine = DataStore.prescriptions[i][3];
                String quantity = txtOrderQuantity.getText();
                String total = txtTotalPrice.getText();

                String orderId = "ORD" + String.format("%03d", DataStore.orderIdCounter);

                DataStore.orders[DataStore.orderCount][0] = orderId;
                DataStore.orders[DataStore.orderCount][1] = patientId;
                DataStore.orders[DataStore.orderCount][2] = rxId;
                DataStore.orders[DataStore.orderCount][3] = medicine;
                DataStore.orders[DataStore.orderCount][4] = quantity;
                DataStore.orders[DataStore.orderCount][5] = DataStore.ORDER_PENDING;
                DataStore.orders[DataStore.orderCount][6] = java.time.LocalDate.now().toString();
                DataStore.orders[DataStore.orderCount][7] = total;
                DataStore.orders[DataStore.orderCount][8] = DataStore.currentUserId;
                
                DataStore.orderCount++;
                DataStore.orderIdCounter++;

         

                javax.swing.JOptionPane.showMessageDialog(this, "Order placed!");

                dispose();
                return;
            }
        }
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void cmbPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPrescriptionActionPerformed
        // TODO add your handling code here:
        loadSelectedPrescription();
    }//GEN-LAST:event_cmbPrescriptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DoctorCreateOrderDialog dialog = new DoctorCreateOrderDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
   private void loadSelectedPrescription() {

    String selected = (String) cmbPrescription.getSelectedItem();
    if (selected == null) return;

    String rxId = selected.split(" - ")[0];

    for (int i = 0; i < DataStore.prescriptionCount; i++) {

        if (DataStore.prescriptions[i][0].equals(rxId)) {

            String patientId = DataStore.prescriptions[i][1];
            String medicine = DataStore.prescriptions[i][3];
            String rxQty = DataStore.prescriptions[i][5];

            // ================= PATIENT NAME (INLINE) =================
            String patientName = "";
            for (int p = 0; p < DataStore.patientCount; p++) {
                if (DataStore.patients[p][0].equals(patientId)) {
                    patientName = DataStore.patients[p][1];
                    break;
                }
            }

            txtPatientName.setText(patientName);
            txtMedicineName.setText(medicine);
            txtQuantity.setText(rxQty);

            // ================= UNIT PRICE (INLINE) =================
            double unitPrice = 0;
            for (int m = 0; m < DataStore.medicineCount; m++) {
                if (DataStore.medicines[m][1].equals(medicine)) {
                    unitPrice = Double.parseDouble(DataStore.medicines[m][3]);
                    break;
                }
            }

            // ================= ORDER QTY =================
            int orderQty = Integer.parseInt(rxQty);
            txtOrderQuantity.setText(String.valueOf(orderQty));

            // ================= TOTAL PRICE =================
            double total = orderQty * unitPrice;

            txtUnitPrice.setText(String.valueOf(unitPrice));
            txtTotalPrice.setText(String.valueOf(total));

            break;
        }
    }
}
   
   private void loadData() {

    cmbPrescription.removeAllItems();

    for (int i = 0; i < DataStore.prescriptionCount; i++) {

        String doctorId = DataStore.prescriptions[i][2];
        String status = DataStore.prescriptions[i][7];

        // only pending + assigned to this doctor
        if (doctorId.equals(DataStore.currentUserId)
                && status.equals(DataStore.RX_PENDING)) {

            String rxId = DataStore.prescriptions[i][0];
            String medicine = DataStore.prescriptions[i][3];
            String patientId = DataStore.prescriptions[i][1];

            cmbPrescription.addItem(rxId + " - " + medicine + " (" + patientId + ")");
        }
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addDoctorOrderPanel;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JComboBox<String> cmbPrescription;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtMedicineName;
    private javax.swing.JLabel txtOrderQuantity;
    private javax.swing.JLabel txtPatientName;
    private javax.swing.JLabel txtQuantity;
    private javax.swing.JLabel txtTotalPrice;
    private javax.swing.JLabel txtUnitPrice;
    // End of variables declaration//GEN-END:variables
}
