/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package epharmacysystem.ui.dialogs;

import epharmacysystem.data.DataStore;
import java.time.LocalDate;

/**
 *
 * @author Zid
 */
public class EditMedicineDialog extends javax.swing.JDialog {
    private String medicineId;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditMedicineDialog.class.getName());

    /**
     * Creates new form AddMedicineDialog
     */
    public EditMedicineDialog(java.awt.Frame parent, boolean modal, DataStore ds, String medicineId) {
        super(parent, modal);
        initComponents();
        this.medicineId = medicineId;
        loadMedicine();
    }
    
    
    private void loadMedicine(){
        int rowIndex = -1;
    
    for (int i = 0; i < DataStore.medicineCount; i++) {
        if (DataStore.medicines[i][0].equals(medicineId)) {
            rowIndex = i;
            break;
        }
    }

    if (rowIndex == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Medicine not found!");
        this.dispose();
        return;
    }
    txtMedicineName.setText(DataStore.medicines[rowIndex][1]);
    txtMedicineStocks.setText(DataStore.medicines[rowIndex][2]);
    txtMedicineUnitPrice.setText(DataStore.medicines[rowIndex][3]);
    txtCompanyName.setText(DataStore.medicines[rowIndex][5]);
    txtMedicineCategory.setText(DataStore.medicines[rowIndex][6]);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtMedicineCategory = new javax.swing.JTextField();
        txtCompanyName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtMedicineStocks = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMedicineName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMedicineUnitPrice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSave.setText("Save");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        jLabel3.setText("Unit Price");

        txtCompanyName.addActionListener(this::txtCompanyNameActionPerformed);

        jLabel2.setText("Stocks");

        jLabel1.setText("Name");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this::btnCancelActionPerformed);

        jLabel5.setText("Category");

        jLabel4.setText("Company");

        txtMedicineName.setColumns(30);
        txtMedicineName.setToolTipText("");
        txtMedicineName.addActionListener(this::txtMedicineNameActionPerformed);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("EDIT MEDICINE");

        txtMedicineUnitPrice.addActionListener(this::txtMedicineUnitPriceActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel4)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMedicineName, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(txtMedicineStocks)
                    .addComponent(txtMedicineCategory)
                    .addComponent(txtCompanyName)
                    .addComponent(txtMedicineUnitPrice))
                .addGap(57, 57, 57))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCompanyName, txtMedicineCategory, txtMedicineName, txtMedicineStocks});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMedicineName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMedicineStocks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMedicineUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMedicineCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (txtMedicineName.getText().isEmpty() || txtMedicineStocks.getText().isEmpty() || 
        txtCompanyName.getText().isEmpty() || txtMedicineCategory.getText().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please fill all fields!");
        return;
    }

    if (!txtMedicineStocks.getText().matches("\\d+")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Stocks must be a whole number!");
        return;
    }

    if (!txtMedicineUnitPrice.getText().matches("\\d*\\.?\\d+")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Unit Price must be a valid price!");
        return;
    }

    // 2. Find the index to UPDATE
    int rowIndex = -1;
    for (int i = 0; i < DataStore.medicineCount; i++) {
        if (DataStore.medicines[i][0].equals(this.medicineId)) {
            rowIndex = i;
            break;
        }
    }

    // 3. Overwrite the existing data (Don't increment medicineCount!)
    if (rowIndex != -1) {
        DataStore.medicines[rowIndex][1] = txtMedicineName.getText();
        DataStore.medicines[rowIndex][2] = txtMedicineStocks.getText();
        DataStore.medicines[rowIndex][3] = txtMedicineUnitPrice.getText();
        DataStore.medicines[rowIndex][5] = txtCompanyName.getText();
        DataStore.medicines[rowIndex][6] = txtMedicineCategory.getText();

        javax.swing.JOptionPane.showMessageDialog(this, "Medicine updated successfully!");
        this.dispose();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtCompanyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompanyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompanyNameActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        txtMedicineName.setText("");
        txtMedicineStocks.setText("");
        txtCompanyName.setText("");
        txtMedicineCategory.setText("");
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtMedicineNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicineNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicineNameActionPerformed

    private void txtMedicineUnitPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicineUnitPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicineUnitPriceActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtCompanyName;
    private javax.swing.JTextField txtMedicineCategory;
    private javax.swing.JTextField txtMedicineName;
    private javax.swing.JTextField txtMedicineStocks;
    private javax.swing.JTextField txtMedicineUnitPrice;
    // End of variables declaration//GEN-END:variables
}
