/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package epharmacysystem.ui.dialogs;

import epharmacysystem.data.DataStore;
import java.time.LocalDate;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Zid
 */
public class EditOrderStatusDialog extends javax.swing.JDialog {
    private String orderId;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditOrderStatusDialog.class.getName());

    /**
     * Creates new form AddMedicineDialog
     */
    public EditOrderStatusDialog(java.awt.Frame parent, boolean modal, DataStore ds, String orderId) {
        super(parent, modal);
        initComponents();
        this.orderId = orderId;
        loadOrder();
    }
    
    
    private void loadOrder(){
        cmbOrderStatus.setModel(new DefaultComboBoxModel<>(new String[]{
            DataStore.ORDER_PENDING,
            DataStore.ORDER_APPROVED,
            DataStore.ORDER_DELIVERED,
            DataStore.ORDER_REJECTED
        }));
        
        int rowIndex = -1;
    
        for (int i = 0; i < DataStore.orderCount; i++) {
            if (DataStore.orders[i][0].equals(orderId)) {
                rowIndex = i;
                break;
            }
        }

        if (rowIndex == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Order not found!");
            this.dispose();
            return;
        }
        
    String pId = DataStore.orders[rowIndex][1]; // Patient ID (e.g., "P001")
    String mName = DataStore.orders[rowIndex][3]; // Medicine Name (Your orders already store the Name here)
    String dId = DataStore.orders[rowIndex][8]; // Doctor User ID (e.g., "u001")

    // Variables to store found names
    String patientName = pId;
    String doctorFullName = dId;

    // 2. Loop through Patients to find the Patient Name
    for (int i = 0; i < DataStore.patientCount; i++) {
        if (DataStore.patients[i][0].equals(pId)) {
            patientName = DataStore.patients[i][1];
            break;
        }
    }

    // 3. Loop through Users to find the Doctor's Full Name (Index 4 in your users array)
    // We use .length since you don't have a userCount variable
    for (int i = 0; i < DataStore.users.length; i++) {
        if (DataStore.users[i][0].equals(dId)) {
            doctorFullName = DataStore.users[i][4]; // Index 4 is the "Full Name" in your users array
            break;
        }
    }
        
        
      // Set UI labels
    orderid.setText(DataStore.orders[rowIndex][0]);
    patientId.setText(patientName);           
    prescriptionId.setText(DataStore.orders[rowIndex][2]);
    medicineId.setText(mName); // Note: Your DataStore.orders[i][3] already holds the Name "Paracetamol"
    quantity.setText(DataStore.orders[rowIndex][4]);
    cmbOrderStatus.setSelectedItem(DataStore.orders[rowIndex][5]);
    orderDate.setText(DataStore.orders[rowIndex][6]);
    orderPrice.setText(DataStore.orders[rowIndex][7]);
    doctorId.setText(doctorFullName);
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        orderid = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        patientId = new javax.swing.JLabel();
        prescriptionId = new javax.swing.JLabel();
        quantity = new javax.swing.JLabel();
        medicineId = new javax.swing.JLabel();
        orderDate = new javax.swing.JLabel();
        doctorId = new javax.swing.JLabel();
        orderPrice = new javax.swing.JLabel();
        cmbOrderStatus = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSave.setText("Save");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        jLabel3.setText("Prescription ID:");

        jLabel2.setText("Patient ID:");

        jLabel1.setText("Order ID:");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this::btnCancelActionPerformed);

        jLabel5.setText("Quantity:");

        jLabel4.setText("Medicine:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("UPDATE ORDER STATUS");

        orderid.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        orderid.setText("Order Id");

        jLabel8.setText("Order Status:");

        jLabel9.setText("Order Date:");

        jLabel10.setText("Total Price:");

        jLabel11.setText("Placed by:");

        patientId.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        patientId.setText("Patient Id");

        prescriptionId.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        prescriptionId.setText("Prescription Id");

        quantity.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        quantity.setText("10");

        medicineId.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        medicineId.setText("Medicine Name");

        orderDate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        orderDate.setText("YYYY/MM/DD");

        doctorId.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        doctorId.setText("Doctor Name");

        orderPrice.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        orderPrice.setText("199.99");

        cmbOrderStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Status" }));
        cmbOrderStatus.addActionListener(this::cmbOrderStatusActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(quantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(orderid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(patientId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prescriptionId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(medicineId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orderDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(doctorId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orderPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbOrderStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancel, btnSave});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(orderid))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientId))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(prescriptionId))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(medicineId))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantity))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbOrderStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderDate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderPrice))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
      int orderRowIndex = -1;
    for (int i = 0; i < DataStore.orderCount; i++) {
        if (DataStore.orders[i][0].equals(this.orderId)) {
            orderRowIndex = i;
            break;
        }
    }

    if (orderRowIndex != -1) {
        String newOrderStatus = cmbOrderStatus.getSelectedItem().toString();
        String linkedRxId = DataStore.orders[orderRowIndex][2]; // Get the RX ID

        // 1. Update the Order Status
        DataStore.orders[orderRowIndex][5] = newOrderStatus;

        // 2. Find and Update the linked Prescription
        for (int j = 0; j < DataStore.prescriptionCount; j++) {
            if (DataStore.prescriptions[j][0].equals(linkedRxId)) {
                
                // Change status to ACTIVE if order is APPROVED
                if (newOrderStatus.equals(DataStore.ORDER_APPROVED)) {
                    DataStore.prescriptions[j][7] = DataStore.RX_ACTIVE;
                } 
                // Change status to FULFILLED if order is DELIVERED
                else if (newOrderStatus.equals(DataStore.ORDER_DELIVERED)) {
                    DataStore.prescriptions[j][7] = DataStore.RX_FULFILLED;
                }
                else if (newOrderStatus.equals(DataStore.ORDER_REJECTED)) {
                    DataStore.prescriptions[j][7] = DataStore.RX_CANCELLED;
                }

                break; 
            }
        }

        JOptionPane.showMessageDialog(this, "Order updated to: " + newOrderStatus + 
                "\nLinked Prescription " + linkedRxId + " status updated accordingly.");
        this.dispose();
    }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void cmbOrderStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrderStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOrderStatusActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbOrderStatus;
    private javax.swing.JLabel doctorId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel medicineId;
    private javax.swing.JLabel orderDate;
    private javax.swing.JLabel orderPrice;
    private javax.swing.JLabel orderid;
    private javax.swing.JLabel patientId;
    private javax.swing.JLabel prescriptionId;
    private javax.swing.JLabel quantity;
    // End of variables declaration//GEN-END:variables


}

